---
title: Lick Creative
email: oliver.phillips@lickcreative.com
description: |
  Lick are a creative agency based in London.
logo: '/img/lick-logo.png'
baseurl:
url: http://www.lickcreative.com
twitter:
  username: wearelick
# Enter your Google Analytics web tracking code (e.g. UA-24138326-1) to activate tracking
google_analytics: UA-24138326-1
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  home-sections:
    title: Home Sections
    output: false
  lab:
    title: Lab
    output: true
    permalink: "/retail-lab/:path"
  locations:
    title: Locations
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
  social:
    title: Social
    output: false
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: work-cover
    cover_image:
    work_assets:
    - ''
    - ''
    - ''
    image: ''
    2x_image: ''
- scope:
    path: ''
    type: lab
  values:
    layout: lab-cover
    has_title: true
    cover-image: "/uploads/lab/lab_desktop.jpg"
    images:
    - ''
    - ''
    - ''
- scope:
    path: ''
    type: social
  values:
    is shown: false
    image: ''
    url: ''
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
