---
title: Lick Creative | Where ideas come true
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  home-sections:
    title: Home Sections
    output: false
  lab:
    title: Lab
    output: true
    permalink: "/retail-lab/:path"
  locations:
    title: Locations
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: work-page
    cover_image:
    work_assets:
    - ''
    - ''
    - ''
    desktop_image: ''
    mobile_image: ''
- scope:
    path: ''
    type: lab
  values:
    layout: lab_cover
    has_title: true
    cover-image_desktop: "/uploads/lab/lab_desktop.jpg"
    cover-image_mobile: "/uploads/lab/lab_mobile.jpg"
    images:
    - ''
    - ''
    - ''
email: oliver.phillips@lickcreative.com
description: |
  Lick are a creative agency based in London.
baseurl:
url: http://www.lickcreative.com
twitter_username: wearelick
markdown: kramdown
sass:
  style: compressed
