---
title: Lick Creative | Where ideas come true
timezone: UTC
collections:
  case_studies:
    title: Case Studies
    output: true
    permalink: "/case_studies/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: oliver.phillips@lickcreative.com
description: |
  Lick is a creative agency based in London.
baseurl: 
url: https://lickcreative.github.io/
twitter_username: wearelick
markdown: kramdown
