---
title: Lick Creative | Where ideas come true
timezone: UTC
collections:
  home-sections:
    title: Home Sections
    output: false
  clients:
    title: Clients
    output: false
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
  locations:
    title: Locations
    output: false
  lab:
    title: Lab
    output: true
    permalink: "/retail-lab/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: work-page
    cover_image:
    work_assets:
    - ''
    - ''
    - ''
    desktop_image: ''
    mobile_image: ''
- scope:
    path: ''
    type: lab
  values:
    layout: lab_cover
    cover-image_desktop: '/uploads/lab/lab_desktop.jpg'
    cover-image_mobile: '/uploads/lab/lab_mobile.jpg'
    images:
    - ''
email: oliver.phillips@lickcreative.com
description: |
  Lick is a creative agency based in London.
baseurl:
url: http://127.0.0.1:4000/
twitter_username: wearelick
markdown: kramdown
sass:
  style: compressed
