---
title: Lick Creative | Where ideas come true
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  home-sections:
    title: Home Sections
    output: false
  locations:
    title: Locations
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: work-page
    cover_image: 
    work_assets:
    - ''
    - ''
    - ''
    thumbnail-image_mobile@1x: ''
    thumbnail-image_mobile@2x: ''
    thumbnail-image_desktop@1x: ''
    thumbnail-image_desktop@2x: ''
- scope:
    path: ''
    type: case_studies
  values:
    layout: case_study
    client_overview: 
    cover_image: 
    images:
    - ''
email: oliver.phillips@lickcreative.com
description: |
  Lick is a creative agency based in London.
baseurl: 
url: http://127.0.0.1:4000/
twitter_username: wearelick
markdown: kramdown
